---
- name: Ensure user exists
  user:
    name: user1
    state: present
    shell: /bin/bash

- name: Create .ssh directory
  file:
    path: /home/user1/.ssh
    state: directory
    owner: user1
    group: user1
    mode: '0700'

- name: Add authorized key
  authorized_key:
    user: user1
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"
