---
- name: Install vsftpd
  apt:
    name: vsftpd
    state: present
    update_cache: yes

- name: Deploy vsftpd configuration
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart vsftpd

- name: Ensure vsftpd is running and enabled
  service:
    name: vsftpd
    state: started
    enabled: yes
