---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: Deploy dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: '0644'
  notify: Restart dnsmasq

- name: Enable and start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true
